# 1. Usa un'immagine Python ufficiale e leggera come base
FROM python:3.11-slim

# 2. Imposta la cartella di lavoro dentro il container
WORKDIR /app

# 3. Copia il file dei requisiti dal tuo PC al container
COPY requirements.txt .

# 4. Installa le librerie necessarie
RUN pip install --no-cache-dir -r requirements.txt

# 5. Copia il tuo script Python nel container
COPY main.py .

# 6. Comando da eseguire quando il container si avvia
#CMD ["python", "main.py"]
CMD python -u main.py # -u per output non bufferizzato, utile per vedere i log in tempo reale