persistence true
persistence_location /mosquitto/data/

# Diciamo a Mosquitto di stampare i log sul terminale di Docker!
log_dest stdout

# Permette connessioni da altri dispositivi
listener 1883
allow_anonymous true